const ROLES = {
  GESTIONNAIRE: 'GESTIONNAIRE',
  AGENT: 'AGENT',
};

const MISSION_STATUSES = ['cree', 'affectee', 'en_cours', 'terminee'];

const ASSIGNABLE_ROLES = [ROLES.GESTIONNAIRE, ROLES.AGENT];

const PHOTO_LABELS = [
  'Profil gauche - Vue laterale complete cote conducteur',
  'Profil droit - Vue laterale complete cote passager',
  'Face avant - Vue frontale complete du vehicule',
  'Face arriere - Vue arriere complete du vehicule',
  '3/4 avant gauche - Vue diagonale avant gauche',
  '3/4 avant droit - Vue diagonale avant droite',
  '3/4 arriere gauche - Vue diagonale arriere gauche',
  '3/4 arriere droit - Vue diagonale arriere droite',
  'Toit - Vue du dessus',
  'Dessous - Vue du chassis',
  'Interieur general',
  'Coffre ou hayon',
  'Pare-chocs avant',
  'Calandre',
  'Phares avant',
  'Feux de position avant',
  'Capot',
  'Pare-brise',
  'Retroviseurs exterieurs',
  'Cotes du vehicule',
  'Portiere avant gauche',
  'Portiere avant droite',
  'Portiere arriere gauche',
  'Portiere arriere droite',
  'Vitres laterales',
  'Montants de portes',
  'Passages de roues',
  'Pare-chocs arriere',
  'Feux arriere',
  'Hayon ou coffre',
  'Lunette arriere',
  'Plaque dimmatriculation',
  'Echappement',
  'Roue avant gauche',
  'Roue avant droite',
  'Roue arriere gauche',
  'Roue arriere droite',
  'Tableau de bord',
  'Compteurs - Kilometrage et temoins',
  'Volant - Etat et commandes',
  'Levier de vitesse',
  'Frein a main',
  'Pedalier',
  'Console centrale',
  'Siege conducteur - Vue complete',
  'Siege passager avant - Vue complete',
  'Banquette arriere - Vue complete',
  'Garnitures de portes - Interieur',
  'Pavillon - Ciel de toit et eclairage',
  'Tapis de sol',
  'Ceintures de securite',
  'Vue ensemble moteur',
  'Bloc moteur',
  'Batterie',
  'Radiateur',
  'Courroies',
  'Reservoirs - Liquide de frein et direction',
  'Filtres - Air et autres',
  'Etiquette constructeur - Plaque signaletique moteur',
  'Plaque constructeur',
  'Numero VIN',
  'Etiquette pression pneus',
  'Impacts - Chocs rayures et deformtions',
  'Peinture - Eclats corrosion decoloration',
  'Vitres - Fissures eclats bris',
  'Eclairage - Cassures ou oxydation',
  'Plastiques - Fissures ou decolorations',
  'Mecaniques - Fuites ou deformtions',
  'Angles multiples - Dommages sous differents angles',
  'Freinage - Disques et plaquettes',
  'Direction - Jeu et fixations',
  'Suspension - Amortisseurs et ressorts',
  'Echappement - Fixations et corrosion',
  'Eclairage - Controle du fonctionnement',
  'Signalisation - Clignotants et warnings',
];

const LABOR_CATEGORIES = [
  { id: 'tolerie_changement', label: 'Tôlerie (changement)' },
  { id: 'tolerie_dressage', label: 'Tôlerie (dressage)' },
  { id: 'peinture', label: 'Peinture' },
  { id: 'mecanique', label: 'Mécanique' },
  { id: 'electricite', label: 'Électricité' },
  { id: 'bris_glace', label: 'Bris de glace' },
];

module.exports = {
  ROLES,
  MISSION_STATUSES,
  ASSIGNABLE_ROLES,
  PHOTO_LABELS,
  LABOR_CATEGORIES,
};
